
package com.exacttarget.wsdl.partnerapi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;

/**
 * This class was generated by the CXF 2.0.2-incubator
 * Mon Oct 26 11:20:42 EDT 2009
 * Generated source version: 2.0.2-incubator
 * 
 */

public final class Soap_Soap_Client {

    private static final QName SERVICE_NAME = new QName("http://exacttarget.com/wsdl/partnerAPI", "PartnerAPI");

    private Soap_Soap_Client() {
    }

    public static void main(String args[]) throws Exception {

        if (args.length == 0) { 
            System.out.println("please specify wsdl");
            System.exit(1); 
        }
        URL wsdlURL = null;
        File wsdlFile = new File(args[0]);
        try {
            if (wsdlFile.exists()) {
                wsdlURL = wsdlFile.toURL();
            } else {
                wsdlURL = new URL(args[0]);
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
      
        PartnerAPI ss = new PartnerAPI(wsdlURL, SERVICE_NAME);
        Soap port = ss.getSoap();  
        
        {
        System.out.println("Invoking extract...");
        com.exacttarget.wsdl.partnerapi.ExtractRequestMsg _extract_parameters = null;
        com.exacttarget.wsdl.partnerapi.ExtractResponseMsg _extract__return = port.extract(_extract_parameters);
        System.out.println("extract.result=" + _extract__return);


        }
        {
        System.out.println("Invoking execute...");
        com.exacttarget.wsdl.partnerapi.ExecuteRequestMsg _execute_parameters = null;
        com.exacttarget.wsdl.partnerapi.ExecuteResponseMsg _execute__return = port.execute(_execute_parameters);
        System.out.println("execute.result=" + _execute__return);


        }
        {
        System.out.println("Invoking perform...");
        com.exacttarget.wsdl.partnerapi.PerformRequestMsg _perform_parameters = null;
        com.exacttarget.wsdl.partnerapi.PerformResponseMsg _perform__return = port.perform(_perform_parameters);
        System.out.println("perform.result=" + _perform__return);


        }
        {
        System.out.println("Invoking query...");
        com.exacttarget.wsdl.partnerapi.QueryRequestMsg _query_parameters = null;
        com.exacttarget.wsdl.partnerapi.QueryResponseMsg _query__return = port.query(_query_parameters);
        System.out.println("query.result=" + _query__return);


        }
        {
        System.out.println("Invoking retrieve...");
        com.exacttarget.wsdl.partnerapi.RetrieveRequestMsg _retrieve_parameters = null;
        com.exacttarget.wsdl.partnerapi.RetrieveResponseMsg _retrieve__return = port.retrieve(_retrieve_parameters);
        System.out.println("retrieve.result=" + _retrieve__return);


        }
        {
        System.out.println("Invoking describe...");
        com.exacttarget.wsdl.partnerapi.DefinitionRequestMsg _describe_parameters = null;
        com.exacttarget.wsdl.partnerapi.DefinitionResponseMsg _describe__return = port.describe(_describe_parameters);
        System.out.println("describe.result=" + _describe__return);


        }
        {
        System.out.println("Invoking delete...");
        com.exacttarget.wsdl.partnerapi.DeleteRequest _delete_parameters = null;
        com.exacttarget.wsdl.partnerapi.DeleteResponse _delete__return = port.delete(_delete_parameters);
        System.out.println("delete.result=" + _delete__return);


        }
        {
        System.out.println("Invoking configure...");
        com.exacttarget.wsdl.partnerapi.ConfigureRequestMsg _configure_parameters = null;
        com.exacttarget.wsdl.partnerapi.ConfigureResponseMsg _configure__return = port.configure(_configure_parameters);
        System.out.println("configure.result=" + _configure__return);


        }
        {
        System.out.println("Invoking schedule...");
        com.exacttarget.wsdl.partnerapi.ScheduleRequestMsg _schedule_parameters = null;
        com.exacttarget.wsdl.partnerapi.ScheduleResponseMsg _schedule__return = port.schedule(_schedule_parameters);
        System.out.println("schedule.result=" + _schedule__return);


        }
        {
        System.out.println("Invoking create...");
        com.exacttarget.wsdl.partnerapi.CreateRequest _create_parameters = null;
        com.exacttarget.wsdl.partnerapi.CreateResponse _create__return = port.create(_create_parameters);
        System.out.println("create.result=" + _create__return);


        }
        {
        System.out.println("Invoking getSystemStatus...");
        com.exacttarget.wsdl.partnerapi.SystemStatusRequestMsg _getSystemStatus_parameters = null;
        com.exacttarget.wsdl.partnerapi.SystemStatusResponseMsg _getSystemStatus__return = port.getSystemStatus(_getSystemStatus_parameters);
        System.out.println("getSystemStatus.result=" + _getSystemStatus__return);


        }
        {
        System.out.println("Invoking update...");
        com.exacttarget.wsdl.partnerapi.UpdateRequest _update_parameters = null;
        com.exacttarget.wsdl.partnerapi.UpdateResponse _update__return = port.update(_update_parameters);
        System.out.println("update.result=" + _update__return);


        }
        {
        System.out.println("Invoking versionInfo...");
        com.exacttarget.wsdl.partnerapi.VersionInfoRequestMsg _versionInfo_parameters = null;
        com.exacttarget.wsdl.partnerapi.VersionInfoResponseMsg _versionInfo__return = port.versionInfo(_versionInfo_parameters);
        System.out.println("versionInfo.result=" + _versionInfo__return);


        }

        System.exit(0);
    }

}
