
package com.exacttarget.wsdl.partnerapi;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;
import javax.jws.WebMethod;
import javax.jws.WebResult;

/**
 * This class was generated by the CXF 2.0.2-incubator
 * Mon Oct 26 11:20:43 EDT 2009
 * Generated source version: 2.0.2-incubator
 * 
 */

@WebService(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", name = "Soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface Soap {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ExtractResponseMsg")
    @WebMethod(operationName = "Extract", action = "Extract")
    public com.exacttarget.wsdl.partnerapi.ExtractResponseMsg extract(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ExtractRequestMsg")
        com.exacttarget.wsdl.partnerapi.ExtractRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ExecuteResponseMsg")
    @WebMethod(operationName = "Execute", action = "Execute")
    public com.exacttarget.wsdl.partnerapi.ExecuteResponseMsg execute(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ExecuteRequestMsg")
        com.exacttarget.wsdl.partnerapi.ExecuteRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "PerformResponseMsg")
    @WebMethod(operationName = "Perform", action = "Perform")
    public com.exacttarget.wsdl.partnerapi.PerformResponseMsg perform(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "PerformRequestMsg")
        com.exacttarget.wsdl.partnerapi.PerformRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "QueryResponseMsg")
    @WebMethod(operationName = "Query", action = "Query")
    public com.exacttarget.wsdl.partnerapi.QueryResponseMsg query(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "QueryRequestMsg")
        com.exacttarget.wsdl.partnerapi.QueryRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "RetrieveResponseMsg")
    @WebMethod(operationName = "Retrieve", action = "Retrieve")
    public com.exacttarget.wsdl.partnerapi.RetrieveResponseMsg retrieve(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "RetrieveRequestMsg")
        com.exacttarget.wsdl.partnerapi.RetrieveRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "DefinitionResponseMsg")
    @WebMethod(operationName = "Describe", action = "Describe")
    public com.exacttarget.wsdl.partnerapi.DefinitionResponseMsg describe(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "DefinitionRequestMsg")
        com.exacttarget.wsdl.partnerapi.DefinitionRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "DeleteResponse")
    @WebMethod(operationName = "Delete", action = "Delete")
    public com.exacttarget.wsdl.partnerapi.DeleteResponse delete(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "DeleteRequest")
        com.exacttarget.wsdl.partnerapi.DeleteRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ConfigureResponseMsg")
    @WebMethod(operationName = "Configure", action = "Configure")
    public com.exacttarget.wsdl.partnerapi.ConfigureResponseMsg configure(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ConfigureRequestMsg")
        com.exacttarget.wsdl.partnerapi.ConfigureRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ScheduleResponseMsg")
    @WebMethod(operationName = "Schedule", action = "Schedule")
    public com.exacttarget.wsdl.partnerapi.ScheduleResponseMsg schedule(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "ScheduleRequestMsg")
        com.exacttarget.wsdl.partnerapi.ScheduleRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "CreateResponse")
    @WebMethod(operationName = "Create", action = "Create")
    public com.exacttarget.wsdl.partnerapi.CreateResponse create(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "CreateRequest")
        com.exacttarget.wsdl.partnerapi.CreateRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "SystemStatusResponseMsg")
    @WebMethod(operationName = "GetSystemStatus", action = "GetSystemStatus")
    public com.exacttarget.wsdl.partnerapi.SystemStatusResponseMsg getSystemStatus(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "SystemStatusRequestMsg")
        com.exacttarget.wsdl.partnerapi.SystemStatusRequestMsg parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "UpdateResponse")
    @WebMethod(operationName = "Update", action = "Update")
    public com.exacttarget.wsdl.partnerapi.UpdateResponse update(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "UpdateRequest")
        com.exacttarget.wsdl.partnerapi.UpdateRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "VersionInfoResponseMsg")
    @WebMethod(operationName = "VersionInfo", action = "VersionInfo")
    public com.exacttarget.wsdl.partnerapi.VersionInfoResponseMsg versionInfo(
        @WebParam(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters", name = "VersionInfoRequestMsg")
        com.exacttarget.wsdl.partnerapi.VersionInfoRequestMsg parameters
    );
}
