
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.exacttarget.wsdl.partnerapi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;

/**
 * This class was generated by the CXF 2.0.2-incubator
 * Mon Oct 26 11:20:42 EDT 2009
 * Generated source version: 2.0.2-incubator
 * 
 */

@javax.jws.WebService(name = "Soap", serviceName = "PartnerAPI",
                      portName = "Soap",
                      targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", 
                      wsdlLocation = "https://webservice.exacttarget.com/etframework.wsdl" ,
		      endpointInterface = "com.exacttarget.wsdl.partnerapi.Soap")
                      
public class SoapImpl implements Soap {

    private static final Logger LOG = Logger.getLogger(SoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#extract(com.exacttarget.wsdl.partnerapi.ExtractRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.ExtractResponseMsg extract(com.exacttarget.wsdl.partnerapi.ExtractRequestMsg parameters) { 
        LOG.info("Executing operation extract");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.ExtractResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#execute(com.exacttarget.wsdl.partnerapi.ExecuteRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.ExecuteResponseMsg execute(com.exacttarget.wsdl.partnerapi.ExecuteRequestMsg parameters) { 
        LOG.info("Executing operation execute");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.ExecuteResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#perform(com.exacttarget.wsdl.partnerapi.PerformRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.PerformResponseMsg perform(com.exacttarget.wsdl.partnerapi.PerformRequestMsg parameters) { 
        LOG.info("Executing operation perform");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.PerformResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#query(com.exacttarget.wsdl.partnerapi.QueryRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.QueryResponseMsg query(com.exacttarget.wsdl.partnerapi.QueryRequestMsg parameters) { 
        LOG.info("Executing operation query");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.QueryResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#retrieve(com.exacttarget.wsdl.partnerapi.RetrieveRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.RetrieveResponseMsg retrieve(com.exacttarget.wsdl.partnerapi.RetrieveRequestMsg parameters) { 
        LOG.info("Executing operation retrieve");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.RetrieveResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#describe(com.exacttarget.wsdl.partnerapi.DefinitionRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.DefinitionResponseMsg describe(com.exacttarget.wsdl.partnerapi.DefinitionRequestMsg parameters) { 
        LOG.info("Executing operation describe");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.DefinitionResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#delete(com.exacttarget.wsdl.partnerapi.DeleteRequest  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.DeleteResponse delete(com.exacttarget.wsdl.partnerapi.DeleteRequest parameters) { 
        LOG.info("Executing operation delete");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.DeleteResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#configure(com.exacttarget.wsdl.partnerapi.ConfigureRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.ConfigureResponseMsg configure(com.exacttarget.wsdl.partnerapi.ConfigureRequestMsg parameters) { 
        LOG.info("Executing operation configure");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.ConfigureResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#schedule(com.exacttarget.wsdl.partnerapi.ScheduleRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.ScheduleResponseMsg schedule(com.exacttarget.wsdl.partnerapi.ScheduleRequestMsg parameters) { 
        LOG.info("Executing operation schedule");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.ScheduleResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#create(com.exacttarget.wsdl.partnerapi.CreateRequest  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.CreateResponse create(com.exacttarget.wsdl.partnerapi.CreateRequest parameters) { 
        LOG.info("Executing operation create");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.CreateResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#getSystemStatus(com.exacttarget.wsdl.partnerapi.SystemStatusRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.SystemStatusResponseMsg getSystemStatus(com.exacttarget.wsdl.partnerapi.SystemStatusRequestMsg parameters) { 
        LOG.info("Executing operation getSystemStatus");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.SystemStatusResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#update(com.exacttarget.wsdl.partnerapi.UpdateRequest  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.UpdateResponse update(com.exacttarget.wsdl.partnerapi.UpdateRequest parameters) { 
        LOG.info("Executing operation update");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.UpdateResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.exacttarget.wsdl.partnerapi.Soap#versionInfo(com.exacttarget.wsdl.partnerapi.VersionInfoRequestMsg  parameters )*
     */
    public com.exacttarget.wsdl.partnerapi.VersionInfoResponseMsg versionInfo(com.exacttarget.wsdl.partnerapi.VersionInfoRequestMsg parameters) { 
        LOG.info("Executing operation versionInfo");
        System.out.println(parameters);
        try {
            com.exacttarget.wsdl.partnerapi.VersionInfoResponseMsg _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
